-- +goose Up
-- +goose StatementBegin
CREATE SCHEMA IF NOT EXISTS orders;

CREATE TABLE orders.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price BIGINT NOT NULL
);

CREATE TABLE orders.orders (
    id UUID PRIMARY KEY,
    total_price BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'created',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE orders.order_items (
    order_id UUID NOT NULL,
    menu_item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    total_price BIGINT NOT NULL,

    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders.orders (id),
    CONSTRAINT fk_menu_item FOREIGN KEY (menu_item_id) REFERENCES orders.menu_items (id)
);

CREATE TABLE orders.deliveries (
    order_id UUID PRIMARY KEY,

    deliver_at TIMESTAMPTZ,

    courier_name TEXT,
    courier_phone TEXT,

    delivery_address TEXT NOT NULL,
    client_phone TEXT,

    CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) REFERENCES orders.orders (id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
